### ISSUE TITLE
Android SDK unavailable on Jitpack

### ISSUE THREAD

**Issue by raxityo** [proxyco/android-sdk-release#1]
Hello,

We recently noticed that the `android-sdk` packages are unavailable from Jitpack. 

For instance, when we try to fetch the version `1.4.5`, we get the following error:
```sh
> Could not get resource 'https://www.jitpack.io/com/github/proxyco/android-sdk/v1.4.5/android-sdk-v1.4.5.pom'.
	> Could not GET 'https://www.jitpack.io/com/github/proxyco/android-sdk/v1.4.5/android-sdk-v1.4.5.pom'. Received status code 403 from server: Forbidden
```

The packages listed on Jitpack (https://www.jitpack.io/#proxyco/android-sdk) take to error page with the following message:
> Subscription not active

Example: https://www.jitpack.io/com/github/proxyco/android-sdk/v1.4.5/android-sdk-v1.4.5.pom

From the recent GitHub packages activity on this repository, it appears that the SDK is going to be distributed via GitHub packages. But the older versions of SDK are not available in GitHub packages.

Thanks!

**Comment by simonratner** [comment]
This was caused by a jitpack.io availability issue that's now corrected.

**Comment by raxityo** [comment]
Thank you @simonratner 👍
